name: Build alcalculatorhead

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MinGW
        run: choco install mingw

      - name: Compile C program to .exe
        run: |
          cd headtest
          x86_64-w64-mingw32-gcc -o alcalculatorhead.exe alcalculatorhead.c almath.c

      - name: Upload testhead directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: alcalculatorhead
          path: |
            headtest/alcalculatorhead.exe
            headtest/almath.h
            headtest/almath.c
